### ISSUE TITLE
Implement useTimeout hook

### ISSUE THREAD

**Issue by bharat-dussa** [vituarvom/react-smart-utils#15]
## `useTimeout`

**Description**: A hook for managing timeouts, which can be useful for delaying actions like showing or hiding UI elements after a specific period.

### Parameters:
- `callback: () => void` – The function to execute after the delay.
- `delay: number` – The delay time in milliseconds before the `callback` is executed.

### Returns:
- `start: () => void` – A function to start the timeout.
- `clear: () => void` – A function to clear the timeout before it completes.

### Example:

```typescript
import { useTimeout } from 'your-library';

const ExampleComponent = () => {
  const [visible, setVisible] = useState(true);
  const { start, clear } = useTimeout(() => setVisible(false), 3000);

  return (
    <div>
      <button onClick={start}>Hide after 3 seconds</button>
      <button onClick={clear}>Cancel Timeout</button>
      {visible && <p>This will disappear after 3 seconds</p>}
    </div>
  );
};

**Comment by doosabhulaxmi** [comment]
@bharat-dussa i want to slove this issue please assign

**Comment by kalvakeerthi** [comment]
Please assign this issue to me. I want to work on this issue. @bharat-dussa

**Comment by bharat-dussa** [comment]
duplicated issue

**Comment by bharat-dussa** [comment]
#19
