### ISSUE TITLE
Implement useWindowSize hook

### ISSUE THREAD

**Issue by bharat-dussa** [vituarvom/react-smart-utils#16]
## `useWindowSize`

**Description**: A hook that tracks the current size of the browser window and updates whenever the window is resized. This can be useful for responsive designs or when you need to react to window size changes.

### Parameters:
- None

### Returns:
- `width: number` – The current width of the window.
- `height: number` – The current height of the window.

### Example:

```typescript
import { useWindowSize } from 'your-library';

const ExampleComponent = () => {
  const { width, height } = useWindowSize();

  return (
    <div>
      <p>Window width: {width}px</p>
      <p>Window height: {height}px</p>
    </div>
  );
};

**Comment by rachhanari** [comment]
Hi, Please assign this issue to me. I want to contribute.

**Comment by VamshiAdep** [comment]
Hi @bharat please assign this task to. Here

**Comment by bharat-dussa** [comment]
Assigned to @rachhanari
