### ISSUE TITLE
Implement useClipboard hook

### ISSUE THREAD

**Issue by bharat-dussa** [vituarvom/react-smart-utils#17]
## `useClipboard`

**Description**: A hook to copy text to the clipboard. This can be useful for implementing features like "copy to clipboard" buttons.

### Parameters:
- `text: string` – The text you want to copy to the clipboard.

### Returns:
- `copy: () => void` – A function that triggers copying the text to the clipboard.
- `copied: boolean` – A boolean value that indicates whether the text has been successfully copied.

### Example:

```typescript
import { useClipboard } from 'your-library';

const ExampleComponent = () => {
  const { copy, copied } = useClipboard('Hello, world!');

  return (
    <div>
      <button onClick={copy}>
        {copied ? 'Copied!' : 'Copy to clipboard'}
      </button>
    </div>
  );
};

**Comment by ReenaChidrala** [comment]
pls assing me this issue I won't to work on this @bharat-dussa

**Comment by snehadomal** [comment]
i want solve this issue please assign mee @bharat-dussa

**Comment by kalvakeerthi** [comment]
I would like to work on this issue. Please assign this issue to me.@bharat-dussa

**Comment by shirishabolli** [comment]
i would like to work on this issue can u assign thiss to mee?
