### ISSUE TITLE
Implement usePrevious hook

### ISSUE THREAD

**Issue by bharat-dussa** [vituarvom/react-smart-utils#21]
## `usePrevious`

**Description**: A hook that stores the previous value of a variable. This is useful for comparing current and previous values in functional components, such as for detecting changes.

### Parameters:
- `value: T` – The value for which you want to track the previous state.

### Returns:
- `T | undefined` – The previous value of the input variable. The initial value will be `undefined`.

### Example:

```typescript
import { useState } from 'react';
import { usePrevious } from 'your-library';

const ExampleComponent = () => {
  const [count, setCount] = useState(0);
  const previousCount = usePrevious(count);

  return (
    <div>
      <p>Current Count: {count}</p>
      <p>Previous Count: {previousCount}</p>
      <button onClick={() => setCount(c => c + 1)}>Increment</button>
    </div>
  );
};

**Comment by RahulJOD** [comment]
Hi, Please assign this issue to me. I want to contribute.

**Comment by doosabhulaxmi** [comment]
I am interested in this issue please assign @bharat-dussa

**Comment by ReenaChidrala** [comment]
pls assing me this issue I won't to work on this @bharat-dussa

**Comment by bharat-dussa** [comment]
Assigned to @ReenaChidrala
