### ISSUE TITLE
toLower

### ISSUE THREAD

**Issue by bharat-dussa** [vituarvom/react-smart-utils#31]
### `toLower`

Converts a given string to lowercase.

**File**: `src/utils/string/toLower/toLower.ts`
**Test File**: `src/utils/string/toLower/toLower.test.ts`

**Parameters**:
- `str: string`: The input string to convert.

**Returns**:
- `string`: The lowercase version of the input string.

**Example**:
```ts
toLower('Hello World'); // 'hello world'
toLower('React Utils');  // 'react utils'
toLower('STRING');       // 'string'

**Comment by harshitaadam** [comment]
I want to work on this, assign this to me
