### ISSUE TITLE
Add Documentation section to README.md

### ISSUE THREAD

**Issue by bharat-dussa** [vituarvom/react-smart-utils#4]
We have to Documentation section in readme into file

I want contributors help to add this
Join discord link for this:

[Join Discord](https://discord.gg/qNeQBF2Q)

**Comment by vigneshbirru** [comment]
i want to contribution in this project

**Comment by prachidoddi** [comment]
@bharat-dussa ,i want to go with documentation

**Comment by VamshiAdep** [comment]
@bharat-dussa  please assign this task

**Comment by bharat-dussa** [comment]
> @bharat-dussa please assign this task

already assigned to prachi
