### ISSUE TITLE
Create uniqueArray Utility Function

### ISSUE THREAD

**Issue by bharat-dussa** [vituarvom/react-smart-utils#46]
### `uniqueArray`

Removes duplicate values from an array.

**File**: `src/utils/array/uniqueArray/uniqueArray.ts`
**Test File**: `src/utils/array/uniqueArray/uniqueArray.test.ts`

**Parameters**:
- `arr: any[]`: The array to filter.

**Returns**:
- `any[]`: An array of unique values.

**Example**:
```ts
uniqueArray([1, 1, 2, 2, 3]);  // [1, 2, 3]
```

**Comment by doosabhulaxmi** [comment]
@bharat-dussa i want to solve this issue please assign

**Comment by Mefisto04** [comment]
hey @bharat-dussa i want to contribute to this issue, please assign this to me
