### ISSUE TITLE
Create sleep Utility Function

### ISSUE THREAD

**Issue by bharat-dussa** [vituarvom/react-smart-utils#47]
### `sleep`

Pauses execution for a specified number of milliseconds.

**File**:  `src/utils/function/sleep/sleep.ts`
**For Test File**:  `src/utils/function/sleep/sleep.test.ts`

**Parameters**:
- `ms: number`: The number of milliseconds to sleep.

**Returns**:
- `Promise<void>`: A promise that resolves after the specified delay.

**Example**:
```ts
await sleep(1000);  // Pauses for 1 second
```

**Comment by Faraz-Khan-79996** [comment]
I want to work on this issue, please assign it to me.

**Comment by bharat-dussa** [comment]
@Faraz-Khan-79996  Assigned to you!.

**Comment by Sum3l** [comment]
@bharat-dussa Please assign this issue to me. I want to work on this issue.

**Comment by bharat-dussa** [comment]
@Sum3l  please pick another one, already been assigned to Faraz khan
