### ISSUE TITLE
Create sample Utility Function

### ISSUE THREAD

**Issue by bharat-dussa** [vituarvom/react-smart-utils#48]
### `sample`

Returns a random element from an array.

**File**: `src/utils/array/sample/sample.ts`
**Test File**: `src/utils/array/sample/sample.test.ts`

**Parameters**:
- `arr: any[]`: The array to sample from.

**Returns**:
- `any`: A random element from the array.

**Example**:
```ts
sample([1, 2, 3, 4]);  // Randomly returns 1, 2, 3, or 4
```

**Comment by doosabhulaxmi** [comment]
@bharat-dussa  i want to solve this issue please assign

**Comment by Mefisto04** [comment]
hey @bharat-dussa can i work on this issue ? i want to contribute in it

**Comment by Dinesh7864** [comment]
@bharat-dussa  i want to contribute to this taks
