### ISSUE TITLE
Create clamp Utility Function

### ISSUE THREAD

**Issue by bharat-dussa** [vituarvom/react-smart-utils#57]
### `clamp`

Clamps a number within the inclusive range specified by the min and max values.

**File**: `src/utils/math/clamp/clamp.ts`
**Test File**: `src/utils/math/clamp/clamp.test.ts`

**Parameters**:
- `num: number`: The number to clamp.
- `min: number`: The minimum value.
- `max: number`: The maximum value.

**Returns**:
- `number`: The clamped number.

**Example**:
```ts
clamp(5, 1, 10);    // 5
clamp(-3, 0, 10);   // 0
clamp(15, 1, 10);   // 10
```

**Comment by vigneshbirru** [comment]
"I’m excited to contribute to this issue—please guide me on the next steps!"
