### ISSUE TITLE
Chores related to configuration and docs

### ISSUE THREAD

**Issue by bharat-dussa** [vituarvom/react-smart-utils#65]
- [ ] change installation command
- [ ] add `useToggle` usage in README.md
- [ ] add lock files in .gitignore
- [ ] Change Contributing.md file changes

**Comment by bharat-dussa** [comment]
Anyone wants to do changes in Readme please comment here

**Comment by iampearlep** [comment]
> Anyone wants to do changes in Readme please comment here

Could you please assign me?

**Comment by bharat-dussa** [comment]
Yes please.

**Comment by pawar1443** [comment]
Hi, Please assign this issue to me. I want to contribute.
