### ISSUE TITLE
Create throttle Utility Function

### ISSUE THREAD

**Issue by bharat-dussa** [vituarvom/react-smart-utils#69]
### `throttle`

Creates a throttled function that only invokes `func` at most once per `wait` milliseconds.

**File**: `src/utils/function/throttle/throttle.ts`
**Test File**: `src/utils/function/throttle/throttle.test.ts`

**Parameters**:
- `func: Function`: The function to throttle.
- `wait: number`: The number of milliseconds to throttle.

**Returns**:
- `Function`: Returns the new throttled function.

**Example**:
```ts
const throttledFunc = throttle(() => console.log('Hello'), 300);
throttledFunc();
```

**Comment by NawinKumarSharma** [comment]
@bharat-dussa can you assign me?
