### ISSUE TITLE
Create usePrevious Utility Function 

### ISSUE THREAD

**Issue by Mefisto04** [vituarvom/react-smart-utils#87]
I would like to request an enhancement to the documentation for the `usePrevious` hook in `react-smart-utils`. A brief explanation and a sample code snippet would greatly assist users in understanding its functionality.

#### `usePrevious` Hook:
The `usePrevious` hook keeps track of the previous value of a state or prop, useful for scenarios where you need to compare the current value with its previous one.

### Sample Code:
```javascript
import { usePrevious } from 'react-smart-utils';
      
<h2>Previous Count: {previousCount !== undefined ? previousCount : 'N/A'}</h2>

```
### Request:
- **Tags**: Please label this issue with `hacktoberfest`.

**Comment by bharat-dussa** [comment]
@Mefisto04  issue is already been created you can see this here #21
